services:
  whatsapp_web_js_api:
    container_name: whatsapp_web_js_api
    image: brunohenriquy/whatsapp-web-js-api:latest
#    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/usr/src/app/sessions
    environment:
      - SESSION_ID=your_session_id_here
#      - API_KEY=your_api_key_here # OPTIONAL, RECOMMENDED FOR PRODUCTION
#      - MONGODB_URI=your_mongo_db_uri #OPTIONAL, IN CASE YOU WANT TO USE REMOTE AUTH, DON'T FORGET TO ALSO SET THE BACKUP_SYNC_INTERVAL_MS
#      - BACKUP_SYNC_INTERVAL_MS=300000 #OPTIONAL, JUST IN CASE YOU ARE USING REMOTE AUTH -> MONGODB_URI
